baseURL = "https://www.theknightlabs.com/blog"
languageCode = "en-us"
theme = "mediumish-gohugo-theme"
summaryLength = 25
title = "The Knight Labs"
Copyright = "The Knight Labs. All rights reserved."
enableEmoji = true
publishDir = "docs"
canonifyURLs = true
## Main Menu
[[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 1
    url = "../"
[[menu.main]]
    name = "Feature"
    identifier = "feature"
    weight = 2
    url = "../#feature"
[[menu.main]]
    name = "Services"
    identifier = "services"
    weight = 3
    url = "../#services"
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 4
    url = "/"
[[menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 5
    url = "../#contact"
[params]
  logo = "../assets/img/logo-header.jpg"
  description =""
