baseURL = "/"
languageCode = "en-us"
theme = "mediumish-gohugo-theme"
summaryLength = 25
title = "The Knight Labs"
Copyright = "The Knight Labs. All rights reserved."
enableEmoji = true
publishDir = "docs"
## Main Menu
[[menu.main]]
    name = "Home"
    identifier = "blog"
    weight = 200
    url = "/"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 200
    url = "/static/imprint"
[params]
  logo = "../assets/img/logo-header.jpg"
  description =""
